// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFG5DPspauYl6wHvB29q4CHLletpmRSg',
    appId: '1:823459707013:web:38c055be3b9381882f51ec',
    messagingSenderId: '823459707013',
    projectId: 'seminario-lddm-firebase',
    authDomain: 'seminario-lddm-firebase.firebaseapp.com',
    storageBucket: 'seminario-lddm-firebase.firebasestorage.app',
    measurementId: 'G-H68WTJYG36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxKGpC0tG7gj-OUKawH0_DzUj8FEYbaQ',
    appId: '1:823459707013:android:a3af3ec48ca9d5b92f51ec',
    messagingSenderId: '823459707013',
    projectId: 'seminario-lddm-firebase',
    storageBucket: 'seminario-lddm-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVmji8Zn56pxEiP0gsQ2XVwbYmdIqDmU',
    appId: '1:823459707013:ios:1a64318da46500ce2f51ec',
    messagingSenderId: '823459707013',
    projectId: 'seminario-lddm-firebase',
    storageBucket: 'seminario-lddm-firebase.firebasestorage.app',
    androidClientId: '823459707013-mtqr72ki68of0c600r14cegbletk11bm.apps.googleusercontent.com',
    iosClientId: '823459707013-1o108crgjorh6avsogvjkuhbmelgfo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVmji8Zn56pxEiP0gsQ2XVwbYmdIqDmU',
    appId: '1:823459707013:ios:1a64318da46500ce2f51ec',
    messagingSenderId: '823459707013',
    projectId: 'seminario-lddm-firebase',
    storageBucket: 'seminario-lddm-firebase.firebasestorage.app',
    androidClientId: '823459707013-mtqr72ki68of0c600r14cegbletk11bm.apps.googleusercontent.com',
    iosClientId: '823459707013-1o108crgjorh6avsogvjkuhbmelgfo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFG5DPspauYl6wHvB29q4CHLletpmRSg',
    appId: '1:823459707013:web:4bd9d4ceb39cb79e2f51ec',
    messagingSenderId: '823459707013',
    projectId: 'seminario-lddm-firebase',
    authDomain: 'seminario-lddm-firebase.firebaseapp.com',
    storageBucket: 'seminario-lddm-firebase.firebasestorage.app',
    measurementId: 'G-793KPKCRRY',
  );

}